# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# # # # #
# Used as meta-data for 'head.html' among
# other things.
#
# Basic, either your jekyll site's name or
# an organization.
name: "e. j. wang"
description: "Personal site of Eric J. Wang."

# This should be a person of some sort.
author: "eric"

# Would make sense to use the 'name:' above
# here. This is an alternative title.
title: "eric@"

# 'en_US' is the default language. Enter a
# new default language here. Making 'en_US'
# an alternative language. See 'head.html'
lang:

# Default post and page image if it's those
# are unspecified.
image: /assets/images/sun.png

# I just set this to whatever the above
# image value is.
# Could be some other image though.
logo:
#
# # # # #

# URL-stuff, don't forget the 'http...'-part
url: "https://www.ericjwang.com"
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
  - name: "about/contact"
    href: "/about"

plugins:
  - jekyll-seo-tag
